/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/3D/3D/scene.gltf 
Author: abdelghani.0 (https://sketchfab.com/abdelghani.0)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/watch-moroccan-mechanical-31b6cbd5a62846fea08c482239211d18
Title: watch Moroccan mechanical
*/

import React, { Suspense } from 'react'
import { OrbitControls, useGLTF } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'

export default function Scene(props) {
  return (
  <div style={{height:'500px'}}>
  <Canvas camera={{position: [0, 2, 5], zoom: 1}}>
    <OrbitControls/>
    {/* <color attach='background' args={['lightblue']}/> */}
    <hemisphereLight intensity={0.35}/>
    <spotLight
    position={[10, 10, 10]}
    angle={0.3}
    penumbra={1}
    intensity={1}
    castShadow
    />
    <Suspense fallback={null}>
      <Model {...props} />
    </Suspense>
    </Canvas>
    </div>
  )

}

export function Model(props) {
  const { nodes, materials } = useGLTF('/3D/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[111.174, -99.74, 170.162]} rotation={[0, 0.015, 0]} scale={498.919}>
          <group position={[0, 0, -0.057]} scale={[0.427, 0.427, 0.051]}>
            <mesh geometry={nodes.Cylinder_black_watch_0.geometry} material={materials.black_watch} />
            <mesh geometry={nodes.Cylinder_black_watch_0_1.geometry} material={materials.black_watch} />
          </group>
        </group>
        <group position={[111.174, -99.74, 170.162]} rotation={[0, 0.015, 0]} scale={498.919}>
          <mesh geometry={nodes.Cube025_iron_hand001_0.geometry} material={materials['iron_hand.001']} position={[0, 0, -0.056]} rotation={[0, 0, -0.008]} scale={0.009} />
          <mesh geometry={nodes.Cube001_iron_hand001_0.geometry} material={materials['iron_hand.001']} position={[0, 0, -0.059]} rotation={[0.007, -0.002, -0.523]} scale={0.009} />
          <mesh geometry={nodes.Cube002_iron_hand001_0.geometry} material={materials['iron_hand.001']} position={[0, 0, -0.051]} rotation={[0.013, -0.007, -1.045]} scale={0.009} />
        </group>
        <group position={[111.174, -99.74, 170.162]} rotation={[0, 0.015, 0]} scale={498.919}>
          <mesh geometry={nodes.Circle002_tiktok_0.geometry} material={materials.tiktok} position={[0.001, 0, -0.036]} rotation={[-3.133, 0.003, -0.41]} scale={[-0.027, 0.027, 0.027]} />
          <mesh geometry={nodes.Circle001_tiktok_0.geometry} material={materials.tiktok} position={[0.001, 0, -0.038]} rotation={[-Math.PI, 0, 0.526]} scale={[-0.027, 0.027, 0.027]} />
          <mesh geometry={nodes.Circle_tiktok_0.geometry} material={materials.tiktok} position={[0.001, 0, -0.041]} rotation={[3.134, 0.002, 2.099]} scale={[-0.027, 0.027, 0.027]} />
        </group>
        <group position={[111.174, -99.74, 170.162]} rotation={[0, 0.015, 0]} scale={498.919}>
          <mesh geometry={nodes.Spur_Gear001_gear_metalic_0.geometry} material={materials.gear_metalic} position={[0.223, 0.044, -0.069]} rotation={[-Math.PI, 0, 0.004]} scale={[-0.037, 0.037, 0.037]} />
          <mesh geometry={nodes.Spur_Gear_gear_metalic_0.geometry} material={materials.gear_metalic} position={[0.189, -0.182, -0.069]} rotation={[-Math.PI, 0, -0.006]} scale={[-0.038, 0.038, 0.038]} />
        </group>
        <group position={[111.174, -99.74, 170.162]} rotation={[0, 0.015, 0]} scale={498.919}>
          <mesh geometry={nodes.Spur_Gear006_gear_metalic_0.geometry} material={materials.gear_metalic} position={[-0.221, -0.116, -0.154]} rotation={[0, 0, -0.214]} scale={0.042} />
          <mesh geometry={nodes.Spur_Gear005_gear_metalic_0.geometry} material={materials.gear_metalic} position={[-0.171, 0.158, -0.078]} rotation={[0, 0, 0.045]} scale={0.036} />
          <mesh geometry={nodes.Spur_Gear003_gear_metalic_0.geometry} material={materials.gear_metalic} position={[0.008, -0.007, -0.077]} rotation={[0, 0, -0.014]} scale={0.038} />
          <mesh geometry={nodes.Spur_Gear002_gear_metalic_0.geometry} material={materials.gear_metalic} position={[0.223, 0.044, -0.085]} rotation={[Math.PI, 0, 0.043]} scale={[-0.037, 0.037, 0.037]} />
          <mesh geometry={nodes.Cube024_gear_metalic_0.geometry} material={materials.gear_metalic} position={[0.162, 0.215, -0.064]} rotation={[0, 0, 1.499]} scale={0.2} />
        </group>
        <group position={[111.174, -99.74, 170.162]} rotation={[0, 0.015, 0]} scale={498.919}>
          <mesh geometry={nodes.Cylinder026_scratch_0.geometry} material={materials.scratch} position={[-0.223, -0.116, -0.076]} scale={[0.052, 0.052, 0.013]} />
          <mesh geometry={nodes.Cube023_scratch_0.geometry} material={materials.scratch} position={[-0.221, -0.217, -0.064]} scale={0.026} />
          <mesh geometry={nodes.Cube022_scratch_0.geometry} material={materials.scratch} position={[-0.065, -0.233, -0.065]} scale={0.026} />
          <mesh geometry={nodes.Cube021_scratch_0.geometry} material={materials.scratch} position={[-0.065, -0.233, -0.065]} scale={0.026} />
          <mesh geometry={nodes.Cube018_scratch_0.geometry} material={materials.scratch} position={[0.001, -0.317, -0.065]} scale={0.026} />
          <mesh geometry={nodes.Cube017_scratch_0.geometry} material={materials.scratch} position={[0.106, 0.298, -0.065]} rotation={[0, 0, -1.001]} scale={0.026} />
          <mesh geometry={nodes.Cube015_scratch_0.geometry} material={materials.scratch} position={[-0.114, 0.075, -0.069]} scale={0.026} />
        </group>
        <group position={[111.174, -99.74, 170.162]} rotation={[0, 0.015, 0]} scale={498.919}>
          <mesh geometry={nodes.Pin2_0_material_0.geometry} material={materials.material} position={[-0.231, -0.176, -0.084]} rotation={[-1.573, -1.186, 3.13]} scale={0.022} />
          <mesh geometry={nodes.Pin1_0_material_0.geometry} material={materials.material} position={[-0.198, -0.164, -0.084]} rotation={[-1.573, -1.186, 3.13]} scale={0.022} />
          <mesh geometry={nodes.Pallets_0_ruby_0.geometry} material={materials.ruby} position={[-0.198, -0.224, -0.076]} rotation={[-1.589, -1.232, 3.111]} scale={0.022} />
          <mesh geometry={nodes['0'].geometry} material={materials.gear_metalic} position={[-0.231, -0.119, -0.123]} rotation={[-1.56, 0.385, 3.137]} scale={21.892} />
          <mesh geometry={nodes.fixations_0_fixtures_0.geometry} material={materials.fixtures} position={[-0.257, -0.187, -0.138]} rotation={[-1.623, -1.208, 3.083]} scale={0.022} />
          <mesh geometry={nodes.escapement_0_escapement_0.geometry} material={materials.escapement} position={[-0.198, -0.224, -0.076]} rotation={[-1.589, -1.232, 3.111]} scale={0.022} />
          <mesh geometry={nodes.escape_wheel_0_gear_metalic_0.geometry} material={materials.gear_metalic} position={[-0.173, -0.3, -0.096]} rotation={[-1.573, -1.2, 3.129]} scale={0.022} />
          <mesh geometry={nodes.Cylinder018_Silver_0.geometry} material={materials.Silver} position={[-0.302, -0.122, -0.066]} scale={0.004} />
          <mesh geometry={nodes.Balance_Wheel_0_gear_metalic_0.geometry} material={materials.gear_metalic} position={[-0.232, -0.117, -0.112]} rotation={[-1.56, 0.4, 3.137]} scale={0.022} />
        </group>
        <group position={[111.174, -99.74, 170.162]} rotation={[0, 0.015, 0]} scale={498.919}>
          <mesh geometry={nodes.Impulse_Pin_0_ruby001_0.geometry} material={materials['ruby.001']} position={[-0.232, -0.117, -0.108]} rotation={[-1.56, 0.385, 3.137]} scale={0.022} />
          <mesh geometry={nodes.Balance_Axle_0_axle_0.geometry} material={materials.axle} position={[-0.232, -0.117, -0.08]} rotation={[-1.573, -1.186, 3.13]} scale={0.022} />
        </group>
        <group position={[111.174, -99.74, 170.162]} rotation={[0, 0.015, 0]} scale={498.919}>
          <mesh geometry={nodes.Cylinder024_inside_metalblack_0.geometry} material={materials['inside_metal.black']} position={[0.223, 0.044, -0.064]} rotation={[0, 0, 0.32]} scale={[0.026, 0.026, 0.001]} />
          <mesh geometry={nodes.Cylinder023_inside_metalblack_0.geometry} material={materials['inside_metal.black']} position={[0.162, 0.215, -0.064]} rotation={[0, 0, 1.477]} scale={[0.019, 0.019, 0.001]} />
          <mesh geometry={nodes.Cylinder022_inside_metalblack_0.geometry} material={materials['inside_metal.black']} position={[0.189, -0.182, -0.069]} rotation={[0, 0, -0.766]} scale={[0.03, 0.03, 0.002]} />
          <mesh geometry={nodes.Cylinder020_inside_metalblack_0.geometry} material={materials['inside_metal.black']} position={[-0.385, -0.01, -0.063]} scale={[0.011, 0.011, 0.001]} />
          <mesh geometry={nodes.Cylinder011_inside_metalblack_0.geometry} material={materials['inside_metal.black']} position={[0.34, -0.154, -0.063]} scale={[0.016, 0.016, 0.001]} />
          <mesh geometry={nodes.Cylinder010_inside_metalblack_0.geometry} material={materials['inside_metal.black']} position={[0.075, 0.316, -0.064]} scale={[0.027, 0.027, 0.002]} />
          <mesh geometry={nodes.Cylinder009_inside_metalblack_0.geometry} material={materials['inside_metal.black']} position={[-0.13, 0.334, -0.063]} scale={[0.027, 0.027, 0.002]} />
          <mesh geometry={nodes.Cylinder007_inside_metalblack_0.geometry} material={materials['inside_metal.black']} position={[-0.368, 0.099, -0.063]} scale={[0.014, 0.014, 0.001]} />
          <mesh geometry={nodes.Cylinder006_inside_metalblack_0.geometry} material={materials['inside_metal.black']} position={[-0.31, 0.214, -0.063]} scale={[0.026, 0.026, 0.001]} />
          <mesh geometry={nodes.Cylinder005_inside_metalblack_0.geometry} material={materials['inside_metal.black']} position={[-0.16, -0.325, -0.063]} scale={[0.02, 0.02, 0.001]} />
          <mesh geometry={nodes.Cylinder004_inside_metalblack_0.geometry} material={materials['inside_metal.black']} position={[0.039, -0.292, -0.063]} scale={[0.021, 0.021, 0.001]} />
        </group>
        <group position={[111.174, -99.74, 170.162]} rotation={[0, 0.015, 0]} scale={498.919}>
          <mesh geometry={nodes.Cylinder025_plastc_pink_0.geometry} material={materials.plastc_pink} position={[0.199, 0.237, -0.07]} rotation={[0, 0, 0.084]} scale={0.01} />
          <mesh geometry={nodes.Cylinder021_plastc_pink_0.geometry} material={materials.plastc_pink} position={[-0.022, -0.226, -0.067]} scale={0.007} />
          <mesh geometry={nodes.Cylinder019_plastc_pink_0.geometry} material={materials.plastc_pink} position={[-0.252, 0.091, -0.072]} scale={0.012} />
          <mesh geometry={nodes.Cylinder017_plastc_pink_0.geometry} material={materials.plastc_pink} position={[-0.231, -0.321, -0.071]} scale={0.012} />
          <mesh geometry={nodes.Cylinder016_plastc_pink_0.geometry} material={materials.plastc_pink} position={[-0.064, -0.389, -0.071]} scale={0.012} />
          <mesh geometry={nodes.Cylinder015_plastc_pink_0.geometry} material={materials.plastc_pink} position={[0.242, -0.313, -0.071]} scale={0.01} />
          <mesh geometry={nodes.Cylinder013_plastc_pink_0.geometry} material={materials.plastc_pink} position={[-0.063, 0.128, -0.078]} scale={0.018} />
          <mesh geometry={nodes.Cylinder012_plastc_pink_0.geometry} material={materials.plastc_pink} position={[-0.171, 0.158, -0.078]} rotation={[0, 0, 0.045]} scale={0.018} />
          <mesh geometry={nodes.Cylinder008_inside_metalblack001_0.geometry} material={materials['inside_metal.black.001']} position={[-0.293, 0.093, -0.062]} scale={[0.012, 0.012, 0.001]} />
        </group>
        <group position={[111.174, -99.74, 170.162]} rotation={[0, 0.015, 0]} scale={498.919}>
          <group position={[0, 0, -0.063]} rotation={[0, 0, -0.007]} scale={0.019}>
            <mesh geometry={nodes.Cylinder014_plastc_pink001_0.geometry} material={materials['plastc_pink.001']} />
            <mesh geometry={nodes.Cylinder014_inside_metalblack_0.geometry} material={materials['inside_metal.black']} />
          </group>
        </group>
        <group position={[111.174, -99.74, 170.162]} rotation={[0, 0.015, 0]} scale={498.919}>
          <group position={[0, 0, -0.055]} rotation={[-Math.PI, 0, 3.141]} scale={[-0.44, 0.44, 0.001]}>
            <mesh geometry={nodes.Cylinder028_Material004_0.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Cylinder028_Material003_0.geometry} material={materials['Material.003']} />
          </group>
        </group>
        <group position={[111.174, -99.74, 170.162]} rotation={[0, 0.015, 0]} scale={498.919}>
          <mesh geometry={nodes.Cylinder001_Metal001_0.geometry} material={materials['Metal.001']} position={[0, 0, -0.177]} scale={[0.427, 0.427, 0.051]} />
        </group>
        <group position={[111.174, -99.74, 170.162]} rotation={[0, 0.015, 0]} scale={498.919}>
          <mesh geometry={nodes.Cylinder030_black_watch_0.geometry} material={materials.black_watch} position={[-0.453, 0, -0.092]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.055} />
        </group>
        <group position={[111.174, -99.74, 170.162]} rotation={[0, 0.015, 0]} scale={498.919}>
          <group scale={[0.416, 0.416, 0.05]}>
            <mesh geometry={nodes.Cylinder027_Transparent_Glass_0.geometry} material={materials.Transparent_Glass} />
            <mesh geometry={nodes.Cylinder027_Transparent_Glass_0_1.geometry} material={materials.Transparent_Glass} />
          </group>
          <group position={[0, 0, -0.057]} scale={[0.427, 0.427, 0.051]}>
            <mesh geometry={nodes.Cylinder002_black_watch_metal_0.geometry} material={materials.black_watch_metal} />
            <mesh geometry={nodes.Cylinder002_black_watch_metal_0_1.geometry} material={materials.black_watch_metal} />
          </group>
          <mesh geometry={nodes.Plane040_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[0, 0.55, -0.183]} rotation={[-0.837, -0.02, 1.577]} scale={[19.757, 18.42, 19.833]} />
          <mesh geometry={nodes.Plane039_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[0.002, 0.046, -1.106]} rotation={[3.081, 0.005, -1.571]} scale={[-20.153, 18.42, 19.43]} />
          <mesh geometry={nodes.Plane038_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[0.001, -0.251, -0.926]} rotation={[2.745, 0.015, -1.572]} scale={[20.049, 18.42, 19.538]} />
          <mesh geometry={nodes.Plane037_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[0.001, -0.237, -0.945]} rotation={[2.621, 0.018, -1.574]} scale={[19.978, 18.42, 19.61]} />
          <mesh geometry={nodes.Plane036__0.geometry} material={materials['Plane.036__0']} position={[0.002, -0.08, -1.032]} rotation={[2.621, 0.018, -1.574]} scale={[19.978, 18.42, 19.61]} />
          <mesh geometry={nodes.Plane034_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[0.002, -0.08, -1.032]} rotation={[2.621, 0.018, -1.574]} scale={[19.978, 18.42, 19.61]} />
          <mesh geometry={nodes.Plane033_watch_brass_pure001_0.geometry} material={materials['watch_brass_pure.001']} position={[0.002, -0.077, -1.027]} rotation={[2.621, 0.018, -1.574]} scale={[19.978, 18.42, 19.61]} />
          <mesh geometry={nodes.Plane032_watch_brass_pure001_0.geometry} material={materials['watch_brass_pure.001']} position={[0.002, -0.079, -1.036]} rotation={[2.621, 0.018, -1.574]} scale={[19.978, 18.42, 19.61]} />
          <mesh geometry={nodes.Plane031_watch_brass_pure001_0.geometry} material={materials['watch_brass_pure.001']} position={[0.002, -0.083, -1.037]} rotation={[2.621, 0.018, -1.574]} scale={[19.978, 18.42, 19.61]} />
          <mesh geometry={nodes.Plane030_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[-0.155, -1.331, -0.466]} rotation={[2.621, 0.018, -1.574]} scale={[19.978, 18.42, 19.61]} />
          <mesh geometry={nodes.Plane029_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[0.156, 1.494, -0.961]} rotation={[-3.02, 0.007, 1.571]} scale={[20.145, 18.42, 19.439]} />
          <mesh geometry={nodes.Plane028_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[0.155, 1.383, -0.592]} rotation={[-2.681, 0.017, 1.573]} scale={[20.014, 18.42, 19.574]} />
          <mesh geometry={nodes.Plane027_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[0.155, 1.275, -0.424]} rotation={[-2.482, 0.02, 1.575]} scale={[19.885, 18.42, 19.704]} />
          <mesh geometry={nodes.Plane026_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[0.079, 1.498, -0.999]} rotation={[-3.051, 0.006, 1.571]} scale={[20.149, 18.42, 19.434]} />
          <mesh geometry={nodes.Plane025_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[0.078, 1.463, -0.8]} rotation={[-2.882, 0.011, 1.571]} scale={[20.108, 18.42, 19.477]} />
          <mesh geometry={nodes.Plane024_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[0.078, 1.308, -0.468]} rotation={[-2.54, 0.019, 1.575]} scale={[19.925, 18.42, 19.664]} />
          <mesh geometry={nodes.Plane023_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[0.077, 1.243, -0.387]} rotation={[-2.426, 0.02, 1.576]} scale={[19.845, 18.42, 19.744]} />
          <mesh geometry={nodes.Plane022_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[0.077, 0.894, -0.162]} rotation={[-1.871, 0.011, 1.576]} scale={[19.493, 18.42, 20.093]} />
          <mesh geometry={nodes.Plane021_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[0.077, 0.66, -0.139]} rotation={[-1.403, -0.006, 1.573]} scale={[19.448, 18.42, 20.135]} />
          <mesh geometry={nodes.Plane020_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[0.077, 0.75, -0.135]} rotation={[-1.624, 0.002, 1.57]} scale={[19.43, 18.42, 20.153]} />
          <mesh geometry={nodes.Plane019_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[0.077, 0.57, -0.169]} rotation={[-1.012, -0.018, 1.578]} scale={[19.635, 18.42, 19.954]} />
          <mesh geometry={nodes.Plane018_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[0.154, 1.055, -0.232]} rotation={[-2.118, 0.018, 1.578]} scale={[19.627, 18.42, 19.961]} />
          <mesh geometry={nodes.Plane017_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[0.154, 0.816, -0.143]} rotation={[-1.744, 0.007, 1.574]} scale={[19.45, 18.42, 20.134]} />
          <mesh geometry={nodes.Plane016_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[0.154, 0.716, -0.134]} rotation={[-1.549, -0.001, 1.569]} scale={[19.428, 18.42, 20.155]} />
          <mesh geometry={nodes.Plane015_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[0.154, 0.614, -0.15]} rotation={[-1.241, -0.012, 1.577]} scale={[19.505, 18.42, 20.08]} />
          <mesh geometry={nodes.Plane014_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[0.154, 0.56, -0.175]} rotation={[-0.925, -0.019, 1.578]} scale={[19.694, 18.42, 19.895]} />
          <mesh geometry={nodes.Plane012_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[-0.078, -0.559, -0.176]} rotation={[0.771, -0.02, -1.577]} scale={[19.805, 18.42, 19.785]} />
          <mesh geometry={nodes.Plane011_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[-0.077, -1.331, -0.466]} rotation={[2.621, 0.018, -1.574]} scale={[19.978, 18.42, 19.61]} />
          <mesh geometry={nodes.Plane010_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[-0.078, -1.165, -0.269]} rotation={[2.272, 0.02, -1.577]} scale={[19.734, 18.42, 19.856]} />
          <mesh geometry={nodes.Plane009_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[-0.078, -0.525, -0.192]} rotation={[0.971, -0.018, -1.578]} scale={[19.663, 18.42, 19.926]} />
          <mesh geometry={nodes.Plane008_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[-0.078, -0.691, -0.131]} rotation={[1.413, -0.006, -1.573]} scale={[19.446, 18.42, 20.138]} />
          <mesh geometry={nodes.Plane007_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[-0.078, -0.599, -0.158]} rotation={[1.289, -0.01, -1.576]} scale={[19.485, 18.42, 20.1]} />
          <mesh geometry={nodes.Plane006_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[-0.155, -1.261, -0.366]} rotation={[2.465, 0.02, -1.576]} scale={[19.873, 18.42, 19.716]} />
          <mesh geometry={nodes.Plane005_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[-0.155, -0.921, -0.145]} rotation={[1.835, 0.01, -1.576]} scale={[19.478, 18.42, 20.107]} />
          <mesh geometry={nodes.Plane004_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[-0.155, -0.633, -0.144]} rotation={[1.284, -0.011, -1.576]} scale={[19.487, 18.42, 20.098]} />
          <mesh geometry={nodes.Plane003_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[-0.155, -0.57, -0.168]} rotation={[1.143, -0.015, -1.577]} scale={[19.555, 18.42, 20.032]} />
          <mesh geometry={nodes.Plane002_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[-0.155, -0.568, -0.17]} rotation={[1.029, -0.017, -1.578]} scale={[19.624, 18.42, 19.965]} />
          <mesh geometry={nodes.Cylinder029_watch_brass_pure001_0.geometry} material={materials['watch_brass_pure.001']} position={[-0.038, 0.199, -1.065]} rotation={[-3.137, -1.55, -1.046]} scale={[19.978, 19.61, 18.42]} />
          <mesh geometry={nodes.Cube_black_watch_metal_0.geometry} material={materials.black_watch_metal} position={[0, 0.533, -0.144]} rotation={[-0.68, 0, 0]} scale={[0.034, 0.037, 0.04]} />
        </group>
        <mesh geometry={nodes.Cube003_tiktok_0.geometry} material={materials.tiktok} position={[111.839, 60.786, 141.688]} rotation={[-Math.PI / 2, 0, 0]} scale={16.53} />
      </group>
    </group>
  )
}

useGLTF.preload('/3D/scene.gltf')
